### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by fuxuliu** [Wangchentong/Proteus#4]
Hi, this is a great job.
Wondering if you will open source the training code?

Thank you.

**Comment by Wangchentong** [comment]
Hi Fuxu,
Thank you for your interest in our work. Due to our current development plan, we are not planning to open the training code. However, I strongly believe that simply modifying the framediff code with our graph triangle block will significantly improve performance to a similar level.
Chentong
________________________________
From: Fuxu Liu ***@***.***>
Sent: Monday, June 24, 2024 12:41 AM
To: Wangchentong/Proteus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Wangchentong/Proteus] About the training code (Issue #4)


Hi, this is a great job.
Wondering if you will open source the training code?

Thank you.

**Comment by Wangchentong** [comment]
Hi Fuxu,
Thank you for your interest in our work. Due to our current development plan, we are not planning to open the training code. However, I strongly believe that simply modifying the framediff code with our graph triangle block will significantly improve performance to a similar level.
